### ISSUE TITLE
Update to Swagger spec v2

### ISSUE THREAD

**Issue by STRML** [strongloop/loopback-explorer#54]
I think we should wait a few weeks on this anyway because there's some instability (like a recent bug in swagger-ui that defaulted all routes to GET regardless of their verb), but eventually we'll want to update loopback-explorer's JSON output to [Swagger v2](https://github.com/wordnik/swagger-spec/blob/master/versions/2.0.md).

**Comment by nhagen** [comment]
Any update on this?

**Comment by bajtos** [comment]
@nhagen I am afraid upgrading to 2.0 is not a priority for us at the moment. Can you contribute the upgrade yourself?

**Comment by OwenBrotherwood** [comment]
Is there a use case for the nee for Swagger v2.x?
It is possible for loopback to use a v2.x ie v2 spec to remoting metadata.
It is possible for loopback to present a v1.x so that other software can use the api.
Some common software still have not "upgraded" to use Swagger v2 eg postman so it looks like the priority for v2 is correct....

**Comment by bajtos** [comment]
> It is possible for loopback to use a v2.x ie v2 spec to remoting metadata.

LoopBack uses it's own format for describing remoting metadata. loopback-explorer converts from this custom format to Swagger spec.

I suppose we could support both 1.x and 2.x versions of Swagger spec, either expose each version on a different URL, or provide a configuration option so that the developer calling loopback-explorer can decide which version to use.

**Comment by OwenBrotherwood** [comment]
Unless someone has a good use case, there doesn't seem any reason to expose 2.x 
I was just wondering if there was a good use case.
Until there comes some world dominating piece of software that will only use 2.x, 1.x looks ok.

**Comment by nhagen** [comment]
I think this might have originally been an issue for me because I wanted to use swagger-js, which IIRC is 2.0 only right now. I don't remember off the top of my head, however.

My view: If loopback is offering Swagger support as a feature that attracts users, those users are going to expect that it will work with other swagger tools. If there is are no plans to support mainline/future Swagger, it should be forked into "Strongloop API Spec". This is especially true if there are no docs specifying how to use the swagger features with other tools. Otherwise I think there's a lot of confusion about what is and isn't compatible with Loopback.

**Comment by raymondfeng** [comment]
LoopBack can enhance the endpoint to expose swagger 2.0 spec in addition to 1.2. The spec generator can potentially produce different versions per client request.

It should not be too hard to add the 2.0 support. Contributions are welcome!

**Comment by fadeojo** [comment]
I think loopback has set a great standard for Nodejs frameworks and swagger 2.0 should be supported. I have tried to convert the swagger 1.2 Api declaration to 2.0 with no success (swagger tools). Please add support for 2.0. I will try and put in my two cents but I'm still learning. Thanks.

**Comment by STRML** [comment]
FYI, the [advert page at strongloop.com](https://strongloop.com/node-js/api-platform/) says Loopback generates Swagger 2.0 documentation, which is not true.

**Comment by Kampfgnom** [comment]
:+1: Is someone working on this? I will try to find the time to look into it, but that won't be in the next few days or even weeks.

**Comment by raymondfeng** [comment]
We're starting to look into it.

**Comment by sachinhub** [comment]
We are trying to publish API generated via loopback onto wso2 publisher. WSO2 publisher version 1.9 can import API from swagger URL. It expects it to be 2.0 specs.

Any update on when we can expect swagger 2.0 spec URL in loopback from timeline perspective?

**Comment by bajtos** [comment]
FYI: I've just submitted a pull request implementing Swagger Spec 2.0 generator for code review, see https://github.com/strongloop/loopback-explorer/pull/115

**Comment by bajtos** [comment]
The patch has been landed. I'd like to make few more cleanups and improvements before making a new release. You can `npm install strongloop/loopback-explorer` to try the new version before it's released to npm.

**Comment by OwenBrotherwood** [comment]
:+1:
